<?php
$type='TrueTypeUnicode';
$name='DejaVuSans';
$desc=array(
  'Ascent'=>928,
  'Descent'=>-236,
  'CapHeight'=>928,
  'Flags'=>32,
  'FontBBox'=>'[-1021 -463 1793 1232]',
  'ItalicAngle'=>0,
  'StemV'=>87,
  'MissingWidth'=>600
);
$up=-63;
$ut=44;
$cw=array();
$enc='';
$diff='';
$file='DejaVuSans.z';
$originalsize=757076;
// This file is auto-generated by makefont.php
?>